xcodeproj 'Files/JerusalemBiblicalZoo.xcodeproj'
pod 'XCDYouTubeVideoPlayerViewController', '~> 1.1'
pod 'MWPhotoBrowser', '~> 1.4'
pod 'MagicalRecord', '~> 2.2'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'Reachability', '~> 3.1'
